(ocamllex
  (modules lexer)
)

(menhir
  (modules mfcalc)
  (flags -la 2)
)

(executable
 (name openstellina)
 (modes js)
 (modules_without_implementation calc)
 (modules version geolocate comets table_update utils location tabbed_dialog cookie storage altaz astro_utils trans hidemsg msgs messier_catalogue calc mfcalc lexer expr dso_read abell_cnv ngc2000 telescope base_locations openstellina)
 (libraries js_of_ocaml-lwt js_of_ocaml-tyxml yojson base64 cohttp-lwt-jsoo xml-light js_of_ocaml unix)
 (preprocess (pps lwt_ppx js_of_ocaml-ppx))
)

(rule
 (alias build_js)
 (deps src/main.c)
 (action (progn
   (run sh -c "emcc ../../src/main.c -I ../../src -I ../../gsl-2.8 -D DEBUG=0 -D MEMDEBUG1=0 -D MEMDEBUG2=0 -D DCFVERSION=4.0 -D DATE=26/11/2024 -D PATHLINK= ../../src/argparse/argparse.c ../../src/coreUtils/asciiDouble.c ../../src/coreUtils/errorReport.c ../../src/coreUtils/makeRasters.c ../../src/ephemCalc/magnitudeEstimate.c ../../src/ephemCalc/jpl.c ../../src/ephemCalc/orbitalElements.c ../../src/listTools/ltDict.c ../../src/listTools/ltList.c ../../src/listTools/ltMemory.c ../../src/listTools/ltStringProc.c ../../src/mathsTools/julianDate.c ../../src/mathsTools/precess_equinoxes.c ../../src/mathsTools/sphericalAst.c ../../src/settings/settings.c ../../gsl-2.8/sys/infnan.c ../../gsl-2.8/sys/pow_int.c ../../gsl-2.8/sys/hypot.c ../../gsl-2.8/sys/fdiv.c ../../gsl-2.8/err/error.c ../../gsl-2.8/err/stream.c -lm -s WASM=1 -s EXPORTED_FUNCTIONS=[_myFunction,_myFloat,_myAscii,_main] -o my_program.js --preload-file ../../data/header.430@/data/ \
     --preload-file ../../data/dcfbinary.430@/data/ \
     --preload-file ../../data/dcfbinary.cmt@/data/ \
     --preload-file ../../data/dcfbinary.plt@/data/ \
     -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s STACK_SIZE=1048576 \
     -s 'EXPORTED_FUNCTIONS=[_myFunction,_myFloat,_myAscii,_main]'")
 ))
 (targets my_program.js my_program.wasm my_program.data))

(rule
 (alias generate_binary)
 (targets ephem_test.exe)
 (deps src/main.c)
 (action
  (progn
   (run sh -c "cc -Wall -Wno-unknown-pragmas -g -I ../../src -I ../../gsl-2.8 -D DEBUG=1 -D MEMDEBUG1=0 -D MEMDEBUG2=0 -D DCFVERSION=\\\"4.0\\\" -D DATE=\\\"23/09/2024\\\" -D PATHLINK=\\\"/\\\" -D SRCDIR=\\\"../../src/\\\" ../../src/argparse/argparse.c ../../src/coreUtils/asciiDouble.c ../../src/coreUtils/errorReport.c ../../src/coreUtils/makeRasters.c ../../src/ephemCalc/magnitudeEstimate.c ../../src/ephemCalc/jpl.c ../../src/ephemCalc/orbitalElements.c ../../src/listTools/ltDict.c ../../src/listTools/ltList.c ../../src/listTools/ltMemory.c ../../src/listTools/ltStringProc.c ../../src/mathsTools/julianDate.c ../../src/mathsTools/precess_equinoxes.c ../../src/mathsTools/sphericalAst.c ../../src/settings/settings.c ../../src/main.c -o ephem_test.exe ../../gsl-2.8/sys/infnan.c ../../gsl-2.8/sys/pow_int.c ../../gsl-2.8/sys/hypot.c ../../gsl-2.8/sys/fdiv.c ../../gsl-2.8/err/error.c ../../gsl-2.8/err/stream.c -lm"))))

(rule
 (alias generate_dcfbin)
 (targets dcfbinary.cmt dcfbinary.430 dcfbinary.plt)
 (deps ephem_test.exe)
 (action
  (progn
   (run ln -s ../../data/dcfbinary.cmt)
   (run ln -s ../../data/dcfbinary.plt)
   (run ln -s ../../data/dcfbinary.430)
   (run sh -c ./ephem_test.exe --objects=mars --use_orbital_elements=1)
   (run sh -c ./ephem_test.exe --objects=\\"C/2023 A3\\")
   )))

(rule
 (targets version.ml)
 (deps version.ml.in)
 (action
  (with-stdout-to
   %{targets}
   (bash "echo '(* Auto-generated by dune *)\n' \
          && git rev-parse HEAD > git_rev.txt \
          && git log -1 --format='%an' > git_author.txt \
          && sed \"s/%%VERSION%%/2.004/g; s/%%GIT_COMMIT%%/$(cat git_rev.txt)/g; s/%%GIT_AUTHOR%%/$(cat git_author.txt)/g\" %{deps}"))))

(alias
 (name default)
 (deps  dcfbinary.cmt dcfbinary.430 dcfbinary.plt openstellina.bc.js my_program.js my_program.wasm my_program.data))

(env
  (dev
    (flags (:standard -g -w -16 -w -32 -w -52 -w -21 -w -26 -w -27 -w -37 -w -11 -w -33))
    (js_of_ocaml
     (compilation_mode whole_program)
     (flags --pretty --disable genprim --noinline --debug-info --source-map --file=../../catalog.txt --file=../../table3.dat --file=../../ngc2000.dat)
     ) 
  )
)
