let remove' = List.filter (function 
| "!R@result@data" -> false
| "!R@result@message" -> false
| "!R@success" -> false
| "R@code" -> false
| "R@error@chain[0]@name" -> true
| "R@error@data@commandErrors[0]@chain[0]@name" -> true
| "R@error@data@commandErrors[0]@data@data" -> false
| "R@error@data@commandErrors[0]@data@register" -> false
| "R@error@data@commandErrors[0]@name" -> true
| "R@error@name" -> true
| "R@message" -> false
| "R@success" -> false
| "R[0]" -> false
(*
| "R[0]@status@apiVersion" -> false
| "R[0]@status@availableReports" -> false
| "R[0]@status@boardInDebugMode" -> false
| "R[0]@status@boardInitError@chain[0]@name" -> true
| "R[0]@status@boardInitError@chain[1]" -> false
| "R[0]@status@boardInitError@name" -> true
| "R[0]@status@bootCount" -> false
| "R[0]@status@connectedDevices[0]@id" -> false
| "R[0]@status@connectedDevices[0]@name" -> true
| "R[0]@status@currentOperation" -> false
| "R[0]@status@elapsedTime" -> false
| "R[0]@status@initError" -> false
| "R[0]@status@initialized" -> false
| "R[0]@status@logs@bufferPosition" -> false
| "R[0]@status@logs@bufferSize" -> false
| "R[0]@status@logs@numFiles" -> false
| "R[0]@status@masterDeviceId" -> false
| "R[0]@status@motors@ALT@atStop" -> false
| "R[0]@status@motors@ALT@calibrated" -> false
| "R[0]@status@motors@ALT@position" -> false
| "R[0]@status@motors@ALT@state" -> false
| "R[0]@status@motors@AZ@atStop" -> false
| "R[0]@status@motors@AZ@calibrated" -> false
| "R[0]@status@motors@AZ@position" -> false
| "R[0]@status@motors@AZ@state" -> false
| "R[0]@status@motors@DER@atStop" -> false
| "R[0]@status@motors@DER@calibrated" -> false
| "R[0]@status@motors@DER@position" -> false
| "R[0]@status@motors@DER@state" -> false
| "R[0]@status@motors@MAP@atStop" -> false
| "R[0]@status@motors@MAP@calibrated" -> false
| "R[0]@status@motors@MAP@position" -> false
| "R[0]@status@motors@MAP@state" -> false
| "R[0]@status@previousOperations@autoInit@ctx" -> false
| "R[0]@status@previousOperations@autoInit@endTime" -> false
| "R[0]@status@previousOperations@autoInit@error@chain[0]@name" -> true
| "R[0]@status@previousOperations@autoInit@error@name" -> true
| "R[0]@status@previousOperations@autoInit@id" -> false
| "R[0]@status@previousOperations@autoInit@position@latitude" -> false
| "R[0]@status@previousOperations@autoInit@position@longitude" -> false
| "R[0]@status@previousOperations@autoInit@startTime" -> false
| "R[0]@status@previousOperations@autoInit@steps[0]@type" -> false
| "R[0]@status@previousOperations@autoInit@stopped" -> false
| "R[0]@status@previousOperations@autoInit@time" -> false
| "R[0]@status@previousOperations@autoInit@type" -> false
| "R[0]@status@previousOperations@observation" -> false
| "R[0]@status@previousOperations@open" -> false
| "R[0]@status@previousOperations@park@ctx" -> false
| "R[0]@status@previousOperations@park@endTime" -> false
| "R[0]@status@previousOperations@park@error@data@commandErrors[0]@chain[0]@name" -> true
| "R[0]@status@previousOperations@park@error@data@commandErrors[0]@data@data" -> false
| "R[0]@status@previousOperations@park@error@data@commandErrors[0]@data@register" -> false
| "R[0]@status@previousOperations@park@error@data@commandErrors[0]@name" -> true
| "R[0]@status@previousOperations@park@error@name" -> true
| "R[0]@status@previousOperations@park@id" -> false
| "R[0]@status@previousOperations@park@startTime" -> false
| "R[0]@status@previousOperations@park@stopped" -> false
| "R[0]@status@previousOperations@park@type" -> false
| "R[0]@status@previousOperations@plan" -> false
| "R[0]@status@previousOperations@storageAcquisition@count" -> false
| "R[0]@status@previousOperations@storageAcquisition@ctx" -> false
| "R[0]@status@previousOperations@storageAcquisition@endTime" -> false
| "R[0]@status@previousOperations@storageAcquisition@error@name" -> true
| "R[0]@status@previousOperations@storageAcquisition@id" -> false
| "R[0]@status@previousOperations@storageAcquisition@path" -> false
| "R[0]@status@previousOperations@storageAcquisition@requiredCount" -> false
| "R[0]@status@previousOperations@storageAcquisition@startTime" -> false
| "R[0]@status@previousOperations@storageAcquisition@stopped" -> false
| "R[0]@status@previousOperations@storageAcquisition@type" -> false
| "R[0]@status@previousOperations@sunMode" -> false
| "R[0]@status@sensors@defogStatus" -> false
| "R[0]@status@sensors@dewpointDepression" -> false
| "R[0]@status@settings@telescopeName" -> false
| "R[0]@status@settings@usbFileTypes" -> false
| "R[0]@status@shuttingDown" -> false
| "R[0]@status@storage@data@available" -> false
| "R[0]@status@storage@data@size" -> false
| "R[0]@status@storage@system@available" -> false
| "R[0]@status@storage@system@size" -> false
| "R[0]@status@storage@usb" -> false
| "R[0]@status@telescopeId" -> false
| "R[0]@status@timestamp" -> false
| "R[0]@status@update@installedVersion" -> false
| "R[0]@status@update@minimumCompatibleVersion" -> false
| "R[0]@status@update@state" -> false
| "R[0]@status@version" -> false
*)
| "R[1]@apiVersion" -> true
| "R[1]@availableReports" -> false
| "R[1]@boardInDebugMode" -> false
| "R[1]@boardInitError@chain[0]@name" -> true
| "R[1]@boardInitError@chain[1]" -> false
| "R[1]@boardInitError@name" -> true
| "R[1]@bootCount" -> false
| "R[1]@connectedDevices[0]@id" -> false
| "R[1]@connectedDevices[0]@name" -> true
| "R[1]@currentOperation" -> true
| "R[1]@elapsedTime" -> false
| "R[1]@initError" -> true
| "R[1]@initialized" -> true
| "R[1]@logs@bufferPosition" -> false
| "R[1]@logs@bufferSize" -> false
| "R[1]@logs@numFiles" -> false
| "R[1]@masterDeviceId" -> false
| "R[1]@motors@ALT@atStop" -> false
| "R[1]@motors@ALT@calibrated" -> false
| "R[1]@motors@ALT@position" -> true
| "R[1]@motors@ALT@state" -> true
| "R[1]@motors@AZ@atStop" -> false
| "R[1]@motors@AZ@calibrated" -> false
| "R[1]@motors@AZ@position" -> true
| "R[1]@motors@AZ@state" -> true
| "R[1]@motors@DER@atStop" -> false
| "R[1]@motors@DER@calibrated" -> false
| "R[1]@motors@DER@position" -> true
| "R[1]@motors@DER@state" -> true
| "R[1]@motors@MAP@atStop" -> false
| "R[1]@motors@MAP@calibrated" -> false
| "R[1]@motors@MAP@position" -> true
| "R[1]@motors@MAP@state" -> true
(*
| "R[1]@previousOperations@autoInit@ctx" -> false
| "R[1]@previousOperations@autoInit@endTime" -> false
| "R[1]@previousOperations@autoInit@error@chain[0]@name" -> true
| "R[1]@previousOperations@autoInit@error@name" -> true
| "R[1]@previousOperations@autoInit@id" -> false
| "R[1]@previousOperations@autoInit@position@latitude" -> false
| "R[1]@previousOperations@autoInit@position@longitude" -> false
| "R[1]@previousOperations@autoInit@startTime" -> false
| "R[1]@previousOperations@autoInit@steps[0]@type" -> false
| "R[1]@previousOperations@autoInit@stopped" -> false
| "R[1]@previousOperations@autoInit@time" -> false
| "R[1]@previousOperations@autoInit@type" -> false
| "R[1]@previousOperations@observation" -> false
| "R[1]@previousOperations@open" -> false
| "R[1]@previousOperations@park@ctx" -> false
| "R[1]@previousOperations@park@endTime" -> false
| "R[1]@previousOperations@park@error@data@commandErrors[0]@chain[0]@name" -> true
| "R[1]@previousOperations@park@error@data@commandErrors[0]@data@data" -> false
| "R[1]@previousOperations@park@error@data@commandErrors[0]@data@register" -> false
| "R[1]@previousOperations@park@error@data@commandErrors[0]@name" -> true
| "R[1]@previousOperations@park@error@name" -> true
| "R[1]@previousOperations@park@id" -> false
| "R[1]@previousOperations@park@startTime" -> false
| "R[1]@previousOperations@park@stopped" -> false
| "R[1]@previousOperations@park@type" -> false
| "R[1]@previousOperations@plan" -> false
| "R[1]@previousOperations@storageAcquisition@count" -> false
| "R[1]@previousOperations@storageAcquisition@ctx" -> false
| "R[1]@previousOperations@storageAcquisition@endTime" -> false
| "R[1]@previousOperations@storageAcquisition@error@name" -> true
| "R[1]@previousOperations@storageAcquisition@id" -> false
| "R[1]@previousOperations@storageAcquisition@path" -> false
| "R[1]@previousOperations@storageAcquisition@requiredCount" -> false
| "R[1]@previousOperations@storageAcquisition@startTime" -> false
| "R[1]@previousOperations@storageAcquisition@stopped" -> false
| "R[1]@previousOperations@storageAcquisition@type" -> false
| "R[1]@previousOperations@sunMode" -> false
*)
| "R[1]@sensors@defogStatus" -> false
| "R[1]@sensors@dewpointDepression" -> false
| "R[1]@settings@telescopeName" -> false
| "R[1]@settings@usbFileTypes" -> false
| "R[1]@shuttingDown" -> true
| "R[1]@storage@data@available" -> false
| "R[1]@storage@data@size" -> false
| "R[1]@storage@system@available" -> false
| "R[1]@storage@system@size" -> false
| "R[1]@storage@usb" -> false
| "R[1]@telescopeId" -> false
| "R[1]@timestamp" -> false
| "R[1]@update@installedVersion" -> false
| "R[1]@update@minimumCompatibleVersion" -> false
| "R[1]@update@state" -> false
| "R[1]@version" -> false
| "R@result@ALT@flags@STANDSTILL" -> true
| "R@result@AZ@flags@STANDSTILL" -> true
| "R@result@DER@flags@STANDSTILL" -> true
| "R@result@STEL@flags@STANDSTILL" -> true
| "R@result@MAP@flags@STANDSTILL" -> true
| "R@result@DER@angle" -> true
| "R@result@ALT@angle" -> true
| "R@result@MAP@angle" -> true
| "R@result@AZ@angle" -> true
| "R[0]@status@previousOperations@observation@capture@images[0]@url" -> true
| "R[0]@status@previousOperations@observation@capture@images[1]@url" -> true
| "R[0]@status@previousOperations@plan@targets[0]@attempts[0]@lastImage@url" -> true
| "R[0]@status@previousOperations@plan@targets[1]@attempts[1]@lastImage@url" -> true
| "R[0]@status@previousOperations@plan@targets[1]@attempts[4]@lastImage@url" -> true
| "R[1]@previousOperations@observation@capture@images[0]@url" -> true
| "R[1]@previousOperations@observation@capture@images[1]@url" -> true
| "R[1]@previousOperations@plan@targets[0]@attempts[0]@lastImage@url" -> true
| "R[1]@previousOperations@plan@targets[1]@attempts[1]@lastImage@url" -> true
| "R[1]@previousOperations@plan@targets[1]@attempts[4]@lastImage@url" -> true
| _ -> false
)
