let trans = function
| "R[0]@status@apiVersion" -> "apiVersion"
| "R[1]@apiVersion" -> "apiVersion"
| "R[1]@sensors@defogStatus" -> "defogStatus"
| "R[1]@settings@telescopeName" -> "telescopeName"
| "R[1]@telescopeId" -> "telescopeId"
| "R[1]@version" -> "version"
| "R@result@DER@angle" -> "derotation angle"
| "R@result@ALT@angle" -> "altitude angle"
| "R@result@MAP@angle" -> "map angle"
| "R@result@AZ@angle" -> "azimuth angle"
| "R@error@chain[0]@name" -> "extended error name"
| "R@error@data@commandErrors[0]@chain[0]@name" -> "command errors name"
| "R@error@data@commandErrors[0]@name" -> "command errors name"
| "R@error@name" -> "general error name"
| "R[0]@status@boardInitError@chain[0]@name" -> "board init extended error name"
| "R[0]@status@boardInitError@name" -> "board init error name"
| "R[0]@status@connectedDevices[0]@name" -> "first connected device"
| "R[0]@status@previousOperations@autoInit@error@chain[0]@name" -> "status@previousOperations@autoInit@error@chain[0]@name"
| "R[0]@status@previousOperations@autoInit@error@name" -> "status@previousOperations@autoInit@error@name"
| "R[0]@status@previousOperations@park@error@data@commandErrors[0]@chain[0]@name" -> "status@previousOperations@park@error@data@commandErrors[0]@chain[0]@name"
| "R[0]@status@previousOperations@park@error@data@commandErrors[0]@name" -> "status@previousOperations@park@error@data@commandErrors[0]@name"
| "R[0]@status@previousOperations@park@error@name" -> "status@previousOperations@park@error@name"
| "R[0]@status@previousOperations@storageAcquisition@error@name" -> "status@previousOperations@storageAcquisition@error@name"
| "R[1]@boardInitError@chain[0]@name" -> "boardInitError@chain[0]@name"
| "R[1]@boardInitError@name" -> "boardInitError@name"
| "R[1]@connectedDevices[0]@name" -> "connectedDevices[0]@name"
| "R[1]@currentOperation" -> "currentOperation"
| "R[1]@initError" -> "initError"
| "R[1]@initialized" -> "initialized"
| "R[1]@motors@ALT@position" -> "altitude motor position"
| "R[1]@motors@ALT@state" -> "altitude motor state"
| "R[1]@motors@AZ@position" -> "azimuth motor position"
| "R[1]@motors@AZ@state" -> "azimuth motor state"
| "R[1]@motors@DER@position" -> "derotator motor position"
| "R[1]@motors@DER@state" -> "derotator motor state"
| "R[1]@motors@MAP@position" -> "focus motor position"
| "R[1]@motors@MAP@state" -> "focus motor state"
| "R[1]@previousOperations@autoInit@error@chain[0]@name" -> "previousOperations@autoInit@error@chain[0]@name"
| "R[1]@previousOperations@autoInit@error@name" -> "previousOperations@autoInit@error@name"
| "R[1]@previousOperations@park@error@data@commandErrors[0]@chain[0]@name" -> "previousOperations@park@error@data@commandErrors[0]@chain[0]@name"
| "R[1]@previousOperations@park@error@data@commandErrors[0]@name" -> "previousOperations@park@error@data@commandErrors[0]@name"
| "R[1]@previousOperations@park@error@name" -> "previousOperations@park@error@name"
| "R[1]@previousOperations@storageAcquisition@error@name" -> "previousOperations@storageAcquisition@error@name"
| "R[1]@shuttingDown" -> "shuttingDown"
| oth -> oth
